apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
  ports:
  - port: {{ .Values.rabbitmqService.port }}
    protocol: TCP
    name: ctr
  - port: {{ .Values.rabbitmqService.managementPort }}
    protocol: TCP
    name: ui 
  selector:
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
