apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels: 
    app: taskQueue
    compenent: rabbitmq
  name: rabbitmq-service
spec:
 affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution: 
    - weight: 100  
      podAffinityTerm:
        labelSelector:
         matchExpressions:
         - key: rabbitmq-cluster-operator
           operator: In
           values:
           - store
        topologyKey: kubernetes.io/hostname
