apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"tcp-services","namespace":"ingress-nginx"}}
  creationTimestamp: "2021-03-04T21:48:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-04T21:48:28Z"
  name: tcp-services
  namespace: ingress-nginx
  resourceVersion: "901"
  uid: d4cca025-e981-4894-b6af-bcc022163a8e
data:
  1344: "icap-adaptation/icap-service:1344"
  1344: "icap-adaptation/icap-service:1345"