environment:
rabbitmqService:
  name: rabbitmq-service
  port: 5672
  managementPort: 15672
  component: rabbitmq
  app: taskQueue
rabbitmqController:
  name: rabbitmq-controller
  port: 5672
  cpu: 100m
  image: rabbitmq:3-management
  app: taskQueue
  component: rabbitmq
