kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.policyupdateservice.rolename }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "create", "get"]