# This PVC manifest is to be used in conjunction with the
# volumes-existing.yaml example. Create this PVC using
# `kubectl create -f testvolume.yaml`, then submit this
# volumes-existing.yaml example.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glasswalltarget-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  # storageClassName: azurefile
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      usage: glasswalltarget-pv